services:
  - type: web
    name: byte-try
    env: php
    buildCommand: |
      apt-get update && apt-get install -y libicu-dev
      docker-php-ext-install intl
      composer install
    startCommand: ""
