CREATE TABLE `orders` (
    `order_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_number` VARCHAR(50) NOT NULL COMMENT 'Unique order reference (ORD-xxx)',
    `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'Buyer user ID',
    `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `tax_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT 'Tax calculated at 12%',
    `tax_rate` DECIMAL(5,2) NOT NULL DEFAULT 12 COMMENT 'VAT/Tax rate percentage',
    `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT 'Final amount to charge',
    `status` ENUM('pending','confirmed','processing','completed','cancelled','refunded') NOT NULL DEFAULT 'pending' COMMENT 'Order status flow',
    `payment_status` ENUM('unpaid','processing','completed','failed','refunded') NOT NULL DEFAULT 'unpaid',
    `payment_method_id` INT(11) UNSIGNED NULL COMMENT 'Payment method used',
    `tracking_number` VARCHAR(100) NULL COMMENT 'Shipping/Delivery tracking number',
    `delivery_address` TEXT NULL COMMENT 'Encrypted delivery address',
    `buyer_notes` TEXT NULL,
    `admin_notes` TEXT NULL COMMENT 'Internal notes for admin',
    `completed_at` DATETIME NULL COMMENT 'When order was completed',
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL COMMENT 'Soft delete for compliance',
    CONSTRAINT `pk_orders` PRIMARY KEY(`order_id`),
    UNIQUE KEY `order_number` (`order_number`),
    KEY `user_id_status` (`user_id`, `status`),
    KEY `payment_status` (`payment_status`),
    KEY `created_at` (`created_at`),
    KEY `deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
